/**
 * Shared brand detection patterns.
 * Used by:
 * - /api/admin/init-brands (backend: auto-detect brands from products)
 * - CategoryProducts.tsx (frontend: dynamic brand filters per category)
 *
 * Order matters: more specific patterns should come first (first match wins).
 */

export interface BrandPattern {
  name: string
  slug: string
  pattern: RegExp
}

export const BRAND_PATTERNS: BrandPattern[] = [
  { name: 'AMD', slug: 'amd', pattern: /\bAMD\b|\bRYZEN\b|\bATHLON\b|\bRADEON\b|\bRX\s\d/i },
  { name: 'Intel', slug: 'intel', pattern: /\bINTEL\b|\bCORE\s*I[3579]\b|\bPENTIUM\b|\bCELERON\b|\bCORE ULTRA\b|\bARC\s*A[37]\b/i },
  { name: 'NVIDIA', slug: 'nvidia', pattern: /\bNVIDIA\b|\bRTX\b|\bGTX\b|\bGEFORCE\b|\bQUADRO\b|\bGT 1030\b/i },
  { name: 'ASUS', slug: 'asus', pattern: /\bASUS\b|\bROG\b|\bTUF\b|\bPRIME\b|\bPROART\b|\bZENBOOK\b|\bVIVOBOOK\b|\bPN\d/i },
  { name: 'Gigabyte', slug: 'gigabyte', pattern: /\bGIGABYTE\b|\bAORUS\b/i },
  { name: 'MSI', slug: 'msi', pattern: /\bMSI\b|\bSPATIUM\b|\bRAIDER\b|\bTHIN\b|\bCYBORG\b/i },
  { name: 'ASRock', slug: 'asrock', pattern: /\bASROCK\b|\bAS ROCK\b/i },
  { name: 'Biostar', slug: 'biostar', pattern: /\bBIOSTAR\b/i },
  { name: 'Kingston', slug: 'kingstontechnology', pattern: /\bKINGSTON\b|\bDATATRAVELER\b|\bDATA TRAVELER\b|\bA400\b|\bKC3000\b|\bKC600\b|\bDC600\b|\bNV3\b/i },
  { name: 'Corsair', slug: 'corsair', pattern: /\bCORSAIR\b|\bVENGEANCE\b/i },
  { name: 'Samsung', slug: 'samsung', pattern: /\bSAMSUNG\b|\bODYSSEY\b|\bVIEWFINITY\b/i },
  { name: 'Seagate', slug: 'seagate', pattern: /\bSEAGATE\b|\bBARRACUDA\b|\bIRONWOLF\b|\bSKYHAWK\b|\bFIRECUDA\b|\bEXPANSION\b|\bONE TOUCH\b/i },
  { name: 'WD', slug: 'wd', pattern: /\bWESTERN\s*DIGITAL\b|\bWD\b/i },
  { name: 'Toshiba', slug: 'toshiba', pattern: /\bTOSHIBA\b|\bCANVIO\b/i },
  { name: 'Hiksemi', slug: 'hiksemi', pattern: /\bHIKSEMI\b/i },
  { name: 'ADATA / XPG', slug: 'adata', pattern: /\bADATA\b|\bXPG\b|\bGAMMIX\b|\bLEGEND\b|\bSPECTRIX\b|\bSU650\b|\bSU630\b|\bCORE\s*REACTOR\b/i },
  { name: 'Lexar', slug: 'lexar', pattern: /\bLEXAR\b|\bNM610\b|\bNM790\b|\bNQ100\b|\bNQ780\b|\bJUMPDRIVE\b/i },
  { name: 'Crucial', slug: 'crucial', pattern: /\bCRUCIAL\b|\bBX500\b|\bP310\b|\bE100\b/i },
  { name: 'Memox', slug: 'memox', pattern: /\bMEMOX\b/i },
  { name: 'G.Skill', slug: 'gskill', pattern: /\bG\.?SKILL\b|\bTRIDENT\b|\bRIPJAWS\b/i },
  { name: 'Patriot', slug: 'patriot', pattern: /\bPATRIOT\b|\bP300\b|\bP210\b|\bRENEGADE\b/i },
  { name: 'Kioxia', slug: 'kioxia', pattern: /\bKIOXIA\b/i },
  { name: 'Silicon Power', slug: 'silicon-power', pattern: /\bSILICON\s*POWER\b/i },
  { name: 'Leven', slug: 'leven', pattern: /\bLEVEN\b/i },
  { name: 'PNY', slug: 'pny', pattern: /\bPNY\b/i },
  { name: 'SOLIDIGM', slug: 'solidigm', pattern: /\bSOLIDIGM\b/i },
  { name: 'SanDisk', slug: 'sandisk', pattern: /\bSANDISK\b/i },
  { name: 'Team Group', slug: 'teamgroup', pattern: /\bTEAM\s*GROUP\b/i },
  { name: 'Biwin', slug: 'biwin', pattern: /\bBIWIN\b/i },
  { name: 'Cooler Master', slug: 'cooler_master', pattern: /\bCOOLER\s*MASTER\b|\bCM\s*(MASTER|ML|MF)/i },
  { name: 'Thermaltake', slug: 'thermaltake', pattern: /\bTHERMALTAKE\b|\bTt\s*(CT|Liquid|LA|Ring|SWAFAN)/i },
  { name: 'DeepCool', slug: 'deepcool', pattern: /\bDEEPCOOL\b/i },
  { name: 'Noctua', slug: 'noctua', pattern: /\bNOCTUA\b/i },
  { name: 'Arctic', slug: 'arctic', pattern: /\bARCTIC\b/i },
  { name: 'be quiet!', slug: 'be-quiet', pattern: /\bBE\s*QUIET\b|\bDARK\s*POWER\b|\bPURE\s*LOOP\b|\bSILENT\s*LOOP\b/i },
  { name: 'Gamemax', slug: 'gamemax', pattern: /\bGAMEMAX\b/i },
  { name: 'NZXT', slug: 'nzxt', pattern: /\bNZXT\b/i },
  { name: 'Seasonic', slug: 'seasonic', pattern: /\bSEASONIC\b/i },
  { name: 'EVGA', slug: 'evga', pattern: /\bEVGA\b/i },
  { name: 'Aerocool', slug: 'aerocool', pattern: /\bAEROCOOL\b/i },
  { name: 'Sentey', slug: 'sentey', pattern: /\bSENTEY\b/i },
  { name: 'Naceb', slug: 'naceb', pattern: /\bNACEB\b/i },
  { name: 'Kelyx', slug: 'kelyx', pattern: /\bKELYX\b/i },
  { name: 'Arkham', slug: 'arkham', pattern: /\bARKHAM\b/i },
  { name: 'Teros', slug: 'teros', pattern: /\bTEROS\b|\bTE-/i },
  { name: 'Raptor', slug: 'raptor', pattern: /\bRAPTOR\b/i },
  { name: 'E-View', slug: 'e-view', pattern: /\bE[\s\-]?VIEW\b/i },
  { name: 'Cromax', slug: 'cromax', pattern: /\bCROMAX\b/i },
  { name: 'CX', slug: 'cx', pattern: /\bCX\b/i },
  { name: 'Logitech', slug: 'logitech', pattern: /\bLOGITECH\b|\bC920\b|\bC270\b|\bBRIO\b|\bYETI\b/i },
  { name: 'Redragon', slug: 'redragon', pattern: /\bREDRAGON\b/i },
  { name: 'HyperX', slug: 'hyperx', pattern: /\bHYPERX\b|\bCLOUD\b|\bALLOY\b|\bQUADCAST\b/i },
  { name: 'Razer', slug: 'razer', pattern: /\bRAZER\b|\bKRAKEN\b|\bDEATHADDER\b|\bVIPER\b|\bBLACKWIDOW\b|\bHUNSTMAN\b|\bKIYO\b|\bGIGANTUS\b/i },
  { name: 'Genius', slug: 'genius', pattern: /\bGENIUS\b/i },
  { name: 'JBL', slug: 'jbl', pattern: /\bJBL\b|\bQUANTUM\b/i },
  { name: 'Philips', slug: 'philips', pattern: /\bPHILIPS\b|\bEVNIA\b/i },
  { name: 'Klipxtreme', slug: 'klipxtreme', pattern: /\bKLIPXTREME\b/i },
  { name: 'X-tech', slug: 'x-tech', pattern: /\bX[\s\-]?TECH\b/i },
  { name: 'LG', slug: 'lg', pattern: /\bLG\b.*\b(ULTRAGEAR|GRAM|MONITOR|TV|PULGADA|PANTALLA|NOTEBOOK|AIO)\b|\bULTRAGEAR\b|\bLG\s*\d{2}/i },
  { name: 'Dell', slug: 'dell', pattern: /\bDELL\b|\bINSPIRON\b|\bLATITUDE\b|\bALIENWARE\b|\bOPTIPLEX\b/i },
  { name: 'HP', slug: 'hp', pattern: /\bHP\b|\bPAVILION\b|\bOMEN\b|\bVICTUS\b|\bDRAGONFLY\b|\bZBOOK\b|\bELITEDESK\b|\bPRODESK\b/i },
  { name: 'Lenovo', slug: 'lenovo', pattern: /\bLENOVO\b|\bTHINKPAD\b|\bIDEAPAD\b|\bLOQ\b|\bLEGION\b|\bYOGA\b|\bTHINKCENTRE\b|\bIDEACENTRE\b/i },
  { name: 'Acer', slug: 'acer', pattern: /\bACER\b|\bASPIRE\b|\bNITRO\b|\bPREDATOR\b/i },
  { name: 'AOC', slug: 'aoc', pattern: /\bAOC\b|\bAGON\b/i },
  { name: 'BenQ', slug: 'benq', pattern: /\bBENQ\b|\bZOWIE\b/i },
  { name: 'ViewSonic', slug: 'viewsonic', pattern: /\bVIEWSONIC\b/i },
  { name: 'TP-Link', slug: 'tplink', pattern: /\bTP[\s\-]?LINK\b|\bARCHER\b|\bDECO\b|\bTL\s*W\b|\bTAPO\b/i },
  { name: 'Mercusys', slug: 'mercusys', pattern: /\bMERCUSYS\b/i },
  { name: 'Cudy', slug: 'cudy', pattern: /\bCUDY\b/i },
  { name: 'Hikvision', slug: 'hikvision', pattern: /\bHIKVISION\b|\bDS-UPS\b/i },
  { name: 'D-Link', slug: 'dlink', pattern: /\bD[\s\-]?LINK\b/i },
  { name: 'Ubiquiti', slug: 'ubiquiti', pattern: /\bUBIQUITI\b|\bUNIFI\b/i },
  { name: 'Mikrotik', slug: 'mikrotik', pattern: /\bMIKROTIK\b|\bROUTEROS\b/i },
  { name: 'Tenda', slug: 'tenda', pattern: /\bTENDA\b/i },
  { name: 'Aruba', slug: 'aruba', pattern: /\bARUBA\b/i },
  { name: 'GlcFi', slug: 'glcfi', pattern: /\bGlcFi\b/i },
  { name: 'Huawei', slug: 'huawei', pattern: /\bHUAWEI\b|\bEKIT\b/i },
  { name: 'HPE', slug: 'hpe', pattern: /\bHPE\b/i },
  { name: 'Foxbox', slug: 'foxbox', pattern: /\bFOXBOX\b|\bCORVUS\b|\bPYXIS\b|\bWARP\b/i },
  { name: 'Harman Kardon', slug: 'harman', pattern: /\bHARMAN\b|\bKARDON\b/i },
  { name: 'Brother', slug: 'brother', pattern: /\bBROTHER\b/i },
  { name: 'Epson', slug: 'epson', pattern: /\bEPSON\b|\bECOTANK\b|\bWORKFORCE\b|\bPERFECTION\b/i },
  { name: 'Lexmark', slug: 'lexmark', pattern: /\bLEXMARK\b/i },
  { name: 'Canon', slug: 'canon', pattern: /\bCANON\b|\bPIXMA\b/i },
  { name: 'Honeywell', slug: 'honeywell', pattern: /\bHONEYWELL\b/i },
  { name: 'Ocom', slug: 'ocom', pattern: /\bOCOM\b/i },
  { name: 'Pantum', slug: 'pantum', pattern: /\bPANTUM\b/i },
  { name: 'Sapphire', slug: 'sapphire', pattern: /\bSAPPHIRE\b/i },
  { name: 'PowerColor', slug: 'powercolor', pattern: /\bPOWERCOLOR\b|\bPOWER\s*COLOR\b/i },
  { name: 'INNO3D', slug: 'inno3d', pattern: /\bINNO3D\b|\bINNO\s*3D\b/i },
  { name: 'EZVIZ', slug: 'ezviz', pattern: /\bEZVIZ\b/i },
  { name: 'Hilook', slug: 'hilook', pattern: /\bHILOOK\b/i },
  { name: 'Xiaomi', slug: 'xiaomi', pattern: /\bXIAOMI\b|\bROBOROCK\b|\bMI\s*\d{1,2}\b/i },
  { name: 'Nexxt', slug: 'nexxt', pattern: /\bNEXXT\b/i },
  { name: 'Loosafe', slug: 'loosafe', pattern: /\bLOOSAFE\b/i },
  { name: 'Ugreen', slug: 'ugreen', pattern: /\bUGREEN\b/i },
  { name: 'Vention', slug: 'vention', pattern: /\bVENTION\b/i },
  { name: 'APC', slug: 'schneiderelectric', pattern: /\bAPC\b/i },
  { name: 'Eaton', slug: 'eaton', pattern: /\bEATON\b/i },
  { name: 'CyberPower', slug: 'cyberpower', pattern: /\bCYBER\s*POWER\b/i },
  { name: 'Tripp Lite', slug: 'tripp-lite', pattern: /\bTRIPP\s*LITE\b/i },
  { name: 'Targus', slug: 'targus', pattern: /\bTARGUS\b/i },
  { name: 'Noganet', slug: 'noganet', pattern: /\bNOGANET\b|\bXO-/i },
  { name: 'Microsoft', slug: 'microsoft', pattern: /\bMICROSOFT\b|\bXBOX\b/i },
  { name: 'Sony', slug: 'sony', pattern: /\bSONY\b|\bDUALSHOCK\b|\bDUALSENSE\b|\bPS[45]\b/i },
  { name: 'Asustor', slug: 'asustor', pattern: /\bASUSTOR\b/i },
  { name: 'QNAP', slug: 'qnap', pattern: /\bQNAP\b/i },
  { name: 'Synology', slug: 'synology', pattern: /\bSYNOLOGY\b/i },
  { name: 'Intelaid', slug: 'intelaid', pattern: /\bINTELAID\b/i },
  { name: 'Furukawa', slug: 'furukawa', pattern: /\bFURUKAWA\b/i },
  { name: 'Fujitsu', slug: 'fujitsu', pattern: /\bFUJITSU\b|\bFI-/i },
  { name: 'Syx', slug: 'syx', pattern: /\bSYX\b/i },
  { name: 'Thronos', slug: 'thronos', pattern: /\bTHRONOS\b/i },
  { name: 'Motorola', slug: 'motorola', pattern: /\bMOTOROLA\b/i },
]
